language: node_js
branches:
  only:
    - master
node_js:
  - "12.8.0"
cache:
  directories:
    - node_modules # NPM packages
before_install:
  - sudo apt-get update -q
install:
  - npm install
jobs:
  include:
    - stage: test
      script: npm run lint && npm run test